// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace 의류_직원_생산성_예측_프로그램ML.Model
{
    public class ModelOutput
    {
        public float Score { get; set; }
    }
}
