// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace 의류_직원_생산성_예측_프로그램ML.Model
{
    public class ModelInput
    {
        [ColumnName("date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("quarter"), LoadColumn(1)]
        public string Quarter { get; set; }


        [ColumnName("department"), LoadColumn(2)]
        public string Department { get; set; }


        [ColumnName("day"), LoadColumn(3)]
        public string Day { get; set; }


        [ColumnName("team"), LoadColumn(4)]
        public float Team { get; set; }


        [ColumnName("targeted_productivity"), LoadColumn(5)]
        public float Targeted_productivity { get; set; }


        [ColumnName("smv"), LoadColumn(6)]
        public float Smv { get; set; }


        [ColumnName("wip"), LoadColumn(7)]
        public float Wip { get; set; }


        [ColumnName("over_time"), LoadColumn(8)]
        public float Over_time { get; set; }


        [ColumnName("incentive"), LoadColumn(9)]
        public float Incentive { get; set; }


        [ColumnName("idle_time"), LoadColumn(10)]
        public float Idle_time { get; set; }


        [ColumnName("idle_men"), LoadColumn(11)]
        public float Idle_men { get; set; }


        [ColumnName("no_of_style_change"), LoadColumn(12)]
        public float No_of_style_change { get; set; }


        [ColumnName("no_of_workers"), LoadColumn(13)]
        public float No_of_workers { get; set; }


        [ColumnName("actual_productivity"), LoadColumn(14)]
        public float Actual_productivity { get; set; }


    }
}
